version: '3.8'
services:

  server:
    image: akashmondal0/snaapio-backend:1.7-beta
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Keep this to allow Docker commands
      - ./jobs:/app/jobs
    networks:
      - monitoring
    env_file:
      - .env
    # restart: unless-stopped

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - server
  #   restart: unless-stopped
  #   networks:
  #     - monitoring

networks:
  monitoring:
    driver: bridge
