version: '3.8'
services:
  server:
    image: akashmondal0/skylight-backend:latest
    ports:
      - "5000:5000"
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf