version: "3.7"

services:
  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 'admin'  # Default Grafana admin password
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring
    restart: always

  k6:
    image: grafana/k6:latest
    container_name: k6
    command: run --out prometheus=http://prometheus:9090 /scripts/loadtest.js  # Path to your k6 script
    volumes:
      - ./scripts:/scripts  # Path to the directory where your k6 script is located
    networks:
      - monitoring
    restart: always

networks:
  monitoring:
    driver: bridge
