{
 "title": "GraphQL All Total Requests",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "GraphQL All Total Requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (route) (\r\n  http_requests_total{\r\n    route!=\"/v1/metrics\",\r\n    route!=\"/favicon.ico\",\r\n    route!=\"/\",\r\n    app=\"snaapio-server\",\r\n    status_code=\"200\"\r\n  }\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage Percentage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total[1m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GraphQL All Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (route) (\r\n  http_requests_total{\r\n    route!=\"/v1/metrics\",\r\n    route!=\"/favicon.ico\",\r\n    route!=\"/\",\r\n    app=\"snaapio-server\",\r\n    status_code=\"200\"\r\n  }\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"nestjs-app\", level!=\"info\"} |= ``"
    }
   ]
  }
 ]
}